#! /bin/bash
# Usage: add-image /path/to/original name

orig=$1
name=$2

convert -resize 320x -quality 50%% $orig ~/Code/vks-testing/images/$name-s.jpg
convert -resize 640x -quality 50%% $orig ~/Code/vks-testing/images/$name-m.jpg
convert -resize 1280x -quality 50%% $orig ~/Code/vks-testing/images/$name-l.jpg
convert -resize 2560x -quality 50%% $orig ~/Code/vks-testing/images/$name-xl.jpg

tag="
<img src=\"../../images/$name-s.jpg\"\n
     srcset=\"\n
        ../../images/$name-s.jpg 320w,\n
        ../../images/$name-m.jpg 640w,\n
        ../../images/$name-l.jpg 1280w,\n
        ../../images/$name-xl.jpg 2560w\"\n
     sizes=\"\n
        (max-width: 768px) 100vw,\n
        (min-width: 768px) 80vw,\n
        (min-width: 1920px) 40vw,"\n
     alt=\"$name\" /> 
"

wl-copy $tag
